- name: varprompt module sample
  hosts: local
  connection:local
  vars_prompt:
  - name: username
    prompt: "Enter username"
    private: no
  - name: password 
    prompt: "Enter password"
    private: yes
  tasks: 
    - name: print userid and pwd
      ansible.builtin.debug:
       msg: "enterd user is {{username}} and password is {{password}}"
  