- name: filters sample
  hosts: local
  connection: local
  vars:
    topic: python,devops,c,yml
    designation: "DevOps Engineer"
    ipchk:  54.87.29.285
    tagmap:
      name: ansible # map
      project:  devops
      component: catalogue
    taglist:
       [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "project",
            "value": "devops"
        },
        {
            "key": "component",
            "value": "catalogue"
        }
       ]

  tasks: 
  - name: filters default task
    ansible.builtin.debug:
     msg: "Hi Pragathi, {{ GREET | default('GOOD MNG') }}"

  - name: filter split the string to list
    ansible.builtin.debug:    
     msg: "{{ topic | split (',') }} "

  - name: filter split the map to list
    ansible.builtin.debug:    
     msg: "{{ tagmap | dict2items }}"

  - name: filter split the list to map
    ansible.builtin.debug:    
     msg: "{{ taglist | items2dict }}"

  - name: read 02-student.yaml
    ansible.builtin.set_fact:
      student_ymlvar: "{{ lookup('file', '02-student.yaml' ) | from_yaml }}"

  - name: convert 02-student.yaml to json
    ansible.builtin.debug:
      msg: "{{ student_ymlvar | to_nice_json }}"

  - name: convert string to uppper case
    ansible.builtin.debug:
      msg: "{{ designation | upper }}"

  - name: convert string to lower case
    ansible.builtin.debug:
      msg: "{{ designation | lower }}"            

  - name: to check given ip is ipv4 or not
    ansible.builtin.debug:
      msg: "{{ ipchk | ansible.utils.ipv4 }}"  